---
# tasks file for cephadmin
- name: Add Red Hat ceph-mon-rpms
  yum_repository:
    name: ceph-mon-rpms
    description: Ceph Mon YUM repo
    file: ceph
    baseurl: "http://{{ reposerver }}/repos/rhel-7-server-rhceph-{{ rh_ceph_version }}-mon-rpms"
    gpgcheck: no
    enabled: yes
  when: reposerver is defined

- name: Add Red Hat ceph-osd-rpms
  yum_repository:
    name: ceph-osd-rpms
    description: Ceph Osd YUM repo
    file: ceph
    baseurl: "http://{{ reposerver }}/repos/rhel-7-server-rhceph-{{ rh_ceph_version }}-osds-rpms"
    gpgcheck: no
    enabled: yes
  when: reposerver is defined

- name: Add Red Hat ceph-console-rpms
  yum_repository:
    name: ceph-console-rpms
    description: Ceph Console YUM repo
    file: ceph
    baseurl: "http://{{ reposerver }}/repos/rhel-7-server-rhceph-{{ rh_ceph_version }}-console-rpms"
    gpgcheck: no
    enabled: yes
  when: reposerver is defined

- name: Add Red Hat ceph-installer-rpms
  yum_repository:
    name: ceph-installer-rpms
    description: Ceph Installer YUM repo
    file: ceph
    baseurl: "http://{{ reposerver }}/repos/rhel-7-server-rhceph-{{ rh_ceph_version }}-installer-rpms"
    gpgcheck: no
    enabled: yes
  when: reposerver is defined
